# Generated by Django 5.1.1 on 2024-09-21 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_tbl_register_tbl_slide'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_provider',
            fields=[
                ('providerName', models.CharField(max_length=50, null=True)),
                ('businessName', models.CharField(max_length=50, null=True)),
                ('contact', models.IntegerField(null=True)),
                ('email', models.EmailField(max_length=100, primary_key=True, serialize=False)),
                ('providerAddress', models.CharField(max_length=50, null=True)),
                ('pincode', models.IntegerField(null=True)),
                ('providerCity', models.CharField(max_length=50, null=True)),
                ('providerAvgCharge', models.CharField(max_length=100, null=True)),
                ('providerDetails', models.CharField(max_length=100, null=True)),
                ('providerServiceImg', models.ImageField(null=True, upload_to='static/service/')),
                ('providerAvgDays', models.IntegerField(null=True)),
                ('providerSvcDate', models.DateField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='tbl_register',
            name='red_date',
        ),
    ]
