# Generated by Django 5.1.1 on 2024-09-26 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_service_provider_delete_tbl_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_provider',
            name='pincode',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_title', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('cost', models.IntegerField()),
                ('avg_time', models.TextField(null=True)),
                ('service_pic', models.ImageField(null=True, upload_to='static/servicepic/')),
                ('provider_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.service_provider')),
            ],
        ),
    ]
