# Generated by Django 5.1.1 on 2024-09-26 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_tbl_service_delete_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('time', models.CharField(max_length=50, null=True)),
                ('detail', models.TextField(null=True)),
                ('address', models.TextField(null=True)),
                ('city', models.IntegerField(null=True)),
                ('pincode', models.IntegerField(null=True)),
                ('payment', models.IntegerField(null=True)),
                ('reqdate', models.DateField(null=True)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.tbl_register')),
                ('providerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.service_provider')),
            ],
        ),
    ]
