# Generated by Django 5.1.1 on 2024-09-26 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_tbl_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_booking',
            name='status',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_booking',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_booking',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_booking',
            name='providerid',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_booking',
            name='reqdate',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
