# Generated by Django 5.1.1 on 2024-09-27 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_tbl_booking_status_alter_tbl_booking_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_register',
            name='id',
        ),
        migrations.AlterField(
            model_name='tbl_register',
            name='email',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
