# Generated by Django 5.1.6 on 2025-04-08 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_remove_tbl_register_id_alter_tbl_register_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service_provider',
            old_name='avg_price',
            new_name='per_square',
        ),
    ]
